### ISSUE TITLE
can't type $ caracter

### ISSUE THREAD

**Issue by jenish-unoapp** [King2500/PhpAdvancedAutoComplete#10]
whenever I try to write $(Shift+4) from my keyboard it doesn't doing anything and throwing this error in console 

 NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V

**Comment by King2500** [comment]
Are you sure this is caused by this plugin (PHP Advanced AutoComplete)? 
Does this still occur when you disable this plugin?

Have you also installed "Extended Code Sense"?
They have the same issue:
https://github.com/ivan-veselovsky/repka/issues/4
https://github.com/ivan-veselovsky/repka/issues/3

**Comment by jenish-unoapp** [comment]
Yes Its from  "Extended Code Sense" and not from this "PHP Advanced AutoComplete" 
Thank you for the reply.
