### ISSUE TITLE
Wrong unsetting suggestion

### ISSUE THREAD

**Issue by nazar-pc** [King2500/PhpAdvancedAutoComplete#3]
```php
...
foreach ($id as &$i) {
	$i = $this->read($table, $data_model, $i);
}
return $id;
...
```
There is no need to unset `$i` after cycle.

**Comment by King2500** [comment]
Please report to JetBrains:
https://youtrack.jetbrains.com/issues/WI

It has nothing to do with this Community plugin.

**Comment by nazar-pc** [comment]
But it was suggested by this plugin

**Comment by nazar-pc** [comment]
I'm sorry, reported to wrong repo.
