### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by justmemaarten** [King2500/PhpAdvancedAutoComplete#8]
How can i use the shortcuts?

**Comment by King2500** [comment]
I'm not sure what you mean?

**Comment by mattdeclaire** [comment]
Came here to ask the same question. I typed `date('`, (which autocompletes to `date('')`, and I expected the menu to open at that point. But, nothing happened. I searched around for a key combo to activate it, but gave up. I finally just started typing the `date()` formats I knew, and that's then the context menu opened. I'm not sure if that is intended behavior or not, but seems like it could cause common confusion.

**Comment by King2500** [comment]
When your cursor is between quotes, just press `Ctrl`+`Space`:
```php
date('<cursor-here>')
```
